export type { IconProps } from './types'
export { LinkedInIcon } from './LinkedInIcon'
export { FacebookIcon } from './FacebookIcon'
export { InstagramIcon } from './InstagramIcon'
export { GitHubIcon } from './GitHubIcon'
